### ISSUE TITLE
OpenSSL error

### ISSUE THREAD

**Issue by jtbates** [Scifabric/pybossa#1479]
I am getting the following error when I try to run PyBossa (on Mac OS 10.11.16):
```
$ python run.py
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    from pybossa.core import create_app
  File "/Users/jtbates/pybossa/pybossa/core.py", line 29, in <module>
    from pybossa.extensions import *
  File "/Users/jtbates/pybossa/pybossa/extensions.py", line 117, in <module>
    from newsletter import Newsletter
  File "/Users/jtbates/pybossa/pybossa/newsletter/__init__.py", line 20, in <module>
    import mailchimp
  File "/Users/jtbates/.pyenv/versions/pybossa/lib/python2.7/site-packages/mailchimp.py", line 1, in <module>
    import requests, os.path, logging, sys, time
  File "/Users/jtbates/.pyenv/versions/pybossa/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/jtbates/.pyenv/versions/pybossa/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/Users/jtbates/.pyenv/versions/pybossa/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/jtbates/.pyenv/versions/pybossa/lib/python2.7/site-packages/OpenSSL/SSL.py", line 118, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
```

Here are my package versions:
```
$ pip freeze
alabaster==0.7.10
alembic==0.9.1
appdirs==1.4.3
arrow==0.10.0
asn1crypto==0.21.1
Babel==2.3.4
beautifulsoup4==4.5.3
blinker==1.4
cffi==1.9.1
chardet==2.3.0
colorama==0.3.7
cov-core==1.15.0
coverage==4.3.4
cryptography==1.8.1
cssselect==1.0.1
debtcollector==1.12.0
docopt==0.4.0
docutils==0.13.1
enum34==1.1.6
factory-boy==2.4.1
feedparser==5.2.1
Flask==0.10.1
Flask-Assets==0.12
Flask-Babel==0.9
Flask-Cors==3.0.2
Flask-DebugToolbar==0.10.1
flask-json-multidict==1.0.0
-e git+https://github.com/maxcountryman/flask-login.git@13af160b3fd14dfb5f35f9cdc3863771efe194eb#egg=Flask_Login
Flask-Mail==0.9.1
Flask-Misaka==0.3.0
Flask-OAuthlib==0.9.1
Flask-Plugins==1.6.1
Flask-SQLAlchemy==2.0
Flask-WTF==0.9.5
funcsigs==1.0.2
google-api-python-client==1.5.5
html2text==2014.7.3
httplib2==0.10.3
humanize==0.5.1
idna==2.5
imagesize==0.7.1
ip-associations-python-novaclient-ext==0.2
ipaddress==1.0.18
iso8601==0.1.11
itsdangerous==0.24
Jinja2==2.9.5
jsmin==2.2.1
keyring==10.3
keystoneauth1==2.18.0
libsass==0.12.3
lxml==3.7.3
mailchimp==2.0.9
Mako==1.0.6
Markdown==2.6.8
MarkupSafe==1.0
misaka==1.0.2
mock==2.0.0
monotonic==1.2
msgpack-python==0.4.8
ndg-httpsclient==0.4.2
netaddr==0.7.19
netifaces==0.10.5
nose==1.3.7
nose-cov==1.6
oauth2client==4.0.0
oauthlib==2.0.1
os-diskconfig-python-novaclient-ext==0.1.3
os-networksv2-python-novaclient-ext==0.26
os-virtual-interfacesv2-python-novaclient-ext==0.20
oslo.config==3.23.0
oslo.i18n==3.13.0
oslo.serialization==2.17.0
oslo.utils==3.23.0
packaging==16.8
pbr==1.10.0
Pillow==3.0.0
positional==1.1.1
prettytable==0.7.2
psycopg2==2.7
pyasn1==0.2.3
pyasn1-modules==0.0.8
-e git+https://github.com/Scifabric/pybossa@a8ed8df839a5d4c3f88034accaf2ab652d7f5f2b#egg=pybossa
pycparser==2.17
pygeoip==0.3.2
Pygments==2.2.0
PyJWT==1.4.2
pyOpenSSL==0.15.1
pyparsing==2.2.0
pyrax==1.9.8


python-dateutil==2.6.0


python-editor==1.0.3
python-keystoneclient==3.10.0
python-novaclient==2.27.0
pytz==2016.10
rackspace-auth-openstack==1.3
rackspace-novaclient==2.1
raven==4.2.3
rax-default-network-flags-python-novaclient-ext==0.4.0
rax-scheduled-images-python-novaclient-ext==0.3.1
readability-lxml==0.6.2
redis==2.9.1
rednose==1.2.2
requests==2.13.0
requests-oauthlib==0.8.0
rfc3986==0.4.1
rq==0.4.6
-e git+https://github.com/PyBossa/rq-dashboard.git@4e06e81340c3c273c014ced2dc6a47c88e8eb8f3#egg=rq_dashboard
rq-scheduler==0.5.1
rsa==3.4.2
simplejson==3.10.0
six==1.10.0
snowballstemmer==1.2.1
speaklater==1.3
Sphinx==1.5.3
SQLAlchemy==1.0.5
stevedore==1.21.0
termstyle==0.1.11
times==0.7
twitter==1.17.1
Unidecode==0.4.20
uritemplate==3.0.0
webassets==0.12.1
Werkzeug==0.12
wrapt==1.10.8
WTForms==1.0.5
```

**Comment by teleyinex** [comment]
Hi,

It looks like there's a bug in pyopensl (see [this](https://github.com/mwrlabs/drozer/issues/239) and [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843644)). Can you try to upgrade pyopensl and check if it works?

Cheers

**Comment by myme5261314** [comment]
upgrade pyopenssl from version `0.15` to `16.2` will get things right, so `pyopenssl` might need to be pinned to version `16.2` in `setup.py`

**Comment by jtbates** [comment]
Yep, it works for me with pyOpenSSL==16.2. [At least, after running into and fixing [this issue](https://github.com/python-pillow/Pillow/issues/1753) with Pillow on Capitan]. Thanks!

**Comment by therealmarv** [comment]
Especially on macOS there is no OpenSSL (only LibreSSL). I think I've included pyopenssl only as a workaround for old python versions (which is not needed since Ubuntu 16.04). Thanks for pointing out how to solve that. Once the tests lights are green we will hopefully merge it very soon.

@jtbates always using the latest python 2.7.x with Homebrew on macOS. Never had an issue with pillow. Can you explain what you've experienced in detail?

**Comment by jtbates** [comment]
@therealmarv Sorry I didn't save the exact error log, but it was basically the same as posted in the pillow issue
```
File "/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/Image.py", line 66, in <module>
    from PIL import _imaging as core
ImportError: dlopen(/Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/_imaging.so, 2): Symbol not found: _PyUnicodeUCS2_AsLatin1String
  Referenced from: /Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/_imaging.so
  Expected in: flat namespace
 in /Users/ben/.pyenv/versions/burtonmail/lib/python2.7/site-packages/PIL/_imaging.so
```

I'm using Python 2.7.12, but the problem was that [pyenv had switched to a wide Unicode build](https://github.com/pyenv/pyenv/issues/257). It looks like it's been switched back to a narrow build on OSX in newer versions of pyenv, but before finding that out I was able to get things working by explicitly using a narrow build as suggested by the pillow commenters 
```
$ PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs2" pyenv install 2.7.12
```
