### ISSUE TITLE
handle_content_type error

### ISSUE THREAD

**Issue by jtbates** [Scifabric/pybossa#1480]
After installing the latest version of PyBossa on Ubuntu 14.04, I am getting the following error when I visit the site
```
xxx.xxx.xxx.xx - - [11/Mar/2017 22:40:44] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/code/pybossa/pybossa/view/home.py", line 66, in home
    return handle_content_type(response)
  File "/srv/code/pybossa/pybossa/util.py", line 57, in handle_content_type
    if request.headers['Content-Type'] == 'application/json':
  File "/srv/code/pybossa/env/lib/python2.7/site-packages/werkzeug/datastructures.py", line 1348, in __getitem__
    return _unicodify_header_value(self.environ[key])
KeyError: 'CONTENT_TYPE'
```

**Comment by teleyinex** [comment]
That's a bug :-) Thanks for finding it. We'll take a look into it.

**Comment by teleyinex** [comment]
Can you let us know a bit more about the QUERY that you were testing? Because our tests are passing, and there should be a Content-Type in the request no matter what.

**Comment by alexandermendes** [comment]
So I actually encountered this myself when setting up a virtual environment using nginx etc. to replicate how our server is set up. I never quite figured out why the Content-Type header wasn't being sent but apparently it's not guaranteed to exist in all cases, so I just got around that by temporarily replacing all occurrences of `if request.headers['Content-Type'] == 'application/json':` with `if request.headers.get('Content-Type') == 'application/json':`.

**Comment by teleyinex** [comment]
:-) interesting. Let us update the code with that, so you can have it properly done!

**Comment by jtbates** [comment]
I was trying to test installing on AWS EC2 and Google Compute. I'm not sure if the missing Content-Type header is related to their environments, but I got the same error on both. The request was just to load the home page.
`File "/srv/code/pybossa/pybossa/view/home.py", line 66, in home
    return handle_content_type(response)`

**Comment by teleyinex** [comment]
This is really interesting :-) Crowdcrafting is running behind nginx and we have not seen that bug :D We've other server, and they don't have it either. In any case, we will fix it! Thanks for finding the bug!

**Comment by jtbates** [comment]
FWIW, I am also getting the same error on my Mac after getting past the pyOpenSSL problem.

**Comment by daksh-agarwal** [comment]
Running into the same error with this version of Pybossa in my Ubuntu 16.
It's not opening the pybossa homepage at localhost:5000.

**Comment by therealmarv** [comment]
thanks for reporting. This is reproducable with a fresh Vagrant installation:

```
git clone --recursive https://github.com/Scifabric/pybossa
cd pybossa
vagrant up
vagrant ssh
python run.py
```

Output on visiting http://localhost:5000 :
```
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
10.0.2.2 - - [16/Mar/2017 10:24:03] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/vagrant/pybossa/core.py", line 466, in _server_error
    return handle_content_type(response)
  File "/vagrant/pybossa/util.py", line 57, in handle_content_type
    if request.headers['Content-Type'] == 'application/json':
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/datastructures.py", line 1348, in __getitem__
    return _unicodify_header_value(self.environ[key])
KeyError: 'CONTENT_TYPE'
10.0.2.2 - - [16/Mar/2017 10:24:03] "GET /favicon.ico HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/vagrant/pybossa/core.py", line 466, in _server_error
    return handle_content_type(response)
  File "/vagrant/pybossa/util.py", line 57, in handle_content_type
    if request.headers['Content-Type'] == 'application/json':
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/datastructures.py", line 1348, in __getitem__
    return _unicodify_header_value(self.environ[key])
KeyError: 'CONTENT_TYPE'
```
