### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by decervelage** [Scifabric/pybossa#1748]
We recently upgraded to the latest version and implemented LDAP authentication.  Upon completion, errors occur attempting to access any existing project:

```
pybossa.core:ERROR:[2017-11-14 16:42:23,132] Exception on /project/thumbs_down_high_score_100_samples/ [GET] [in /usr/lib/pybossa/env/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/usr/lib/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pybossa/env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./pybossa/view/projects.py", line 561, in details
    project = add_custom_contrib_button_to(project, get_user_id_or_ip(), ps=ps)
  File "./pybossa/cache/helpers.py", line 93, in add_custom_contrib_button_to
    **user_id_or_ip)
  File "./pybossa/cache/helpers.py", line 76, in check_contributing_state
    if ps.overall_progress >= 100:
AttributeError: 'NoneType' object has no attribute 'overall_progress'
```
Digging around a bit, we believe the problem is that a relatively recent update added the `project_stats` table to the database.  The `pybossa.cache.helpers.check_contributing_state()` method appears to assume that there will be a row in that table for every project.  However, this does not appear to be the case for projects that already existed at the time of the upgrade.

Are there some additional upgrade instructions that we missed somewhere?

**Comment by teleyinex** [comment]
Yes, this is something that we didn't include in the docs I'm afraid. Just do the following:

1.- Stop the server
2.- Run the following command: python cli.py update_project stats

Before doing these two steps, take a backup. The issue is that we have created a new table to host all the project stats in order to make it faster. The migration script was not enough, and we have to do it via the cli.py command tool.

Please, try this, and let us know if it fix it.

All the best,

Daniel

**Comment by decervelage** [comment]
That procedure does fix this problem.  Thank you, Daniel.

--Randy

**Comment by teleyinex** [comment]
Glad to hear that it worked.

**Comment by msinkec** [comment]
> 2.- Run the following command: python cli.py update_project stats

There is a small typo in your command; it should be: python cli.py update_project_stats
