### ISSUE TITLE
Vagrant up after a halt fails to start pybossa server

### ISSUE THREAD

**Issue by PranavRam** [Scifabric/pybossa#1799]
Using Vagrant with VirtualBox correctly provisions and starts the environment. The pybossa server starts with the command:

```
python run.py
```

On **halting** the env and starting up again, the above command fails with the following explanation:

```
(pybossa-env) vagrant@vagrant:/vagrant$ python run.py
Slave binds are misssing, adding Master as slave too.
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    app = create_app()
  File "/vagrant/pybossa/core.py", line 62, in create_app
    setup_scheduled_jobs(app)
  File "/vagrant/pybossa/core.py", line 697, in setup_scheduled_jobs
    schedule_job(job, scheduler)
  File "/vagrant/pybossa/jobs.py", line 34, in schedule_job
    scheduled_jobs = scheduler.get_jobs()
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/rq_scheduler/scheduler.py", line 225, in get_jobs
    score_cast_func=epoch_to_datetime)
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/client.py", line 1419, in zrangebyscore
    return self.execute_command(*pieces, **options)
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/client.py", line 464, in execute_command
    connection.send_command(*args)
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/connection.py", line 334, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/connection.py", line 316, in send_packed_command
    self.connect()
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/sentinel.py", line 36, in connect
    self.connect_to(self.connection_pool.get_master_address())
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/sentinel.py", line 68, in get_master_address
    self.service_name)
  File "/home/vagrant/pybossa-env/local/lib/python2.7/site-packages/redis/sentinel.py", line 159, in discover_master
    raise MasterNotFoundError("No master found for %r" % (service_name,))
redis.sentinel.MasterNotFoundError: No master found for 'mymaster'
```

I assume it's due to something with the IP address and not being discoverable. Is there a guide to ensure that this is correctly set up?

Workaround is to **suspend** the environment instead of **halting** it.

Specs:
macOS (10.13.3)
Vagrant (2.6.0)
VirtualBox (201802.02.0)
pybossa (2.9.0)

**Comment by alexandermendes** [comment]
Yep, I've noticed the same thing (and I think it was my fault for introducing it when upgrading the VM). I think it happens if the server is restarted and redis doesn't boot up properly.

For now you can just ssh in and run:

```
sudo -u redis /usr/bin/redis-server /etc/redis/sentinel.conf --sentinel
```

Then you should be able to run `python run.py` as normal.

Probably something in the [redis-sentinel.service](https://github.com/Scifabric/pybossa/blob/master/contrib/redis/redis-sentinel.service) needs to be fixed.

**Comment by therealmarv** [comment]
TO DO: move all redis related things to supervisord.

Actually on production servers we don't rely on system services for redis and sentinel and keep sure redis is up and running with supervisord (reason: better control for us).
