### ISSUE TITLE
Cannot execute pbs create/update_project

### ISSUE THREAD

**Issue by vabatista** [Scifabric/pybossa#1867]
I'm stucked in executing pbs since it cannot parse project.json. I already tried to save it in several encoding formats in vim, but with no sucess. 
I tried a fresh start in tutorial. I have a Anaconda (python 2.7) instalation and used pip to install pbs. I'm also using this instance of pybossa: https://github.com/jvstein/docker-compose-pybossa.

```
[root@npaa4429 ~]# git clone http://github.com/Scifabric/app-flickrperson.git
Cloning into 'app-flickrperson'...
remote: Counting objects: 477, done.
remote: Total 477 (delta 0), reused 0 (delta 0), pack-reused 477
Receiving objects: 100% (477/477), 152.32 KiB | 0 bytes/s, done.
Resolving deltas: 100% (259/259), done.
[root@npaa4429 ~]# cd app-flickrperson/
[root@npaa4429 app-flickrperson]# pbs create_project
Traceback (most recent call last):
  File "/home/anaconda2/bin/pbs", line 11, in <module>
    sys.exit(cli())
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 775, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 784, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 676, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/home/anaconda2/lib/python2.7/site-packages/pbs.py", line 126, in create_project
    res = _create_project(config)
  File "/home/anaconda2/lib/python2.7/site-packages/helpers.py", line 62, in _create_project
    config.project['description'])
  File "/home/anaconda2/lib/python2.7/site-packages/pbclient/__init__.py", line 247, in create_project
    res = _pybossa_req('post', 'project', payload=project)
  File "/home/anaconda2/lib/python2.7/site-packages/pbclient/__init__.py", line 63, in _pybossa_req
    return json.loads(r.text)
  File "/home/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[root@npaa4429 app-flickrperson]#

```

**Comment by teleyinex** [comment]
Hi,

JSON files can be tricky. Can you try your project.json file in an online JSON validator? https://jsonlint.com/

**Comment by vabatista** [comment]
I figured out the problem. 
PBS was trying to access the local server through proxy. The problem is that http response was a http error message, not a JSON.
I configured to direct access and it worked.

**Comment by teleyinex** [comment]
:+1:
