### ISSUE TITLE
Vagrant up never ends and enter state "paused"

### ISSUE THREAD

**Issue by ophyr** [Scifabric/pybossa#1913]
## Environment
I'm on windows 7 but as I don't have any rights on it, I am using a VM to start vagrant environment.
VM : Linux ipf7028 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Vagrant version : 2.2.3
VirtualBox version : 6.0.2

## Background
It took me days to set-up everything working (only vagrant starting)... And now that it is starting, the process seems to work I have multiple message for installations : 
```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-16.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Setting the name of the VM: pybossa_default_1548664551730_33258
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5000 (guest) => 5000 (host) (adapter 1)
    default: 5001 (guest) => 5001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 5.2.22
    default: VirtualBox Version: 6.0
==> default: Mounting shared folders...
    default: /vagrant => /data/molecule/Pybossa/pybossa
==> default: Running provisioner: shell...
    default: Running: inline script
    default: Check if Ansible existing...
    default: update package index files...
    default: install Ansible...
    default: Selecting previously unselected package libyaml-0-2:amd64.
    default: (Reading database ... 
    default: (Reading database ... 5%
    default: (Reading database ... 10%
    default: (Reading database ... 15%
    default: (Reading database ... 20%
    default: (Reading database ... 25%
    default: (Reading database ... 30%
    default: (Reading database ... 35%
    default: (Reading database ... 40%
    default: (Reading database ... 45%
    default: (Reading database ... 50%
    default: (Reading database ... 55%
(Reading database ... 65%abase ... 60%
    default: (Reading database ... 70%
    default: (Reading database ... 75%
    default: (Reading database ... 80%
    default: (Reading database ... 85%
    default: (Reading database ... 90%
    default: (Reading database ... 95%
    default: (Reading database ... 100%
    default: (Reading database ... 
    default: 38412 files and directories currently installed.)
    default: Preparing to unpack .../libyaml-0-2_0.1.6-3_amd64.deb ...
    default: Unpacking libyaml-0-2:amd64 (0.1.6-3) ...
    default: Selecting previously unselected package python-markupsafe.
    default: Preparing to unpack .../python-markupsafe_0.23-2build2_amd64.deb ...
    default: Unpacking python-markupsafe (0.23-2build2) ...
    default: Selecting previously unselected package python-jinja2.
    default: Preparing to unpack .../python-jinja2_2.8-1_all.deb ...
    default: Unpacking python-jinja2 (2.8-1) ...
    default: Selecting previously unselected package python-six.
    default: Preparing to unpack .../python-six_1.10.0-3_all.deb ...
    default: Unpacking python-six (1.10.0-3) ...
    default: Selecting previously unselected package python-ecdsa.
    default: Preparing to unpack .../python-ecdsa_0.13-2_all.deb ...
    default: Unpacking python-ecdsa (0.13-2) ...
    default: Selecting previously unselected package python-paramiko.
    default: Preparing to unpack .../python-paramiko_1.16.0-1ubuntu0.2_all.deb ...
    default: Unpacking python-paramiko (1.16.0-1ubuntu0.2) ...
    default: Selecting previously unselected package python-pkg-resources.
    default: Preparing to unpack .../python-pkg-resources_20.7.0-1_all.deb ...
    default: Unpacking python-pkg-resources (20.7.0-1) ...
    default: Selecting previously unselected package python-yaml.
    default: Preparing to unpack .../python-yaml_3.11-3build1_amd64.deb ...
    default: Unpacking python-yaml (3.11-3build1) ...
    default: Selecting previously unselected package python-httplib2.
    default: Preparing to unpack .../python-httplib2_0.9.1+dfsg-1_all.deb ...
    default: Unpacking python-httplib2 (0.9.1+dfsg-1) ...
    default: Selecting previously unselected package ieee-data.
    default: Preparing to unpack .../ieee-data_20150531.1_all.deb ...
    default: Unpacking ieee-data (20150531.1) ...
    default: Selecting previously unselected package python-netaddr.
    default: Preparing to unpack .../python-netaddr_0.7.18-1_all.deb ...
    default: Unpacking python-netaddr (0.7.18-1) ...
    default: Selecting previously unselected package ansible.
    default: Preparing to unpack .../ansible_2.0.0.2-2ubuntu1.1_all.deb ...
    default: Unpacking ansible (2.0.0.2-2ubuntu1.1) ...
    default: Selecting previously unselected package python-selinux.
    default: Preparing to unpack .../python-selinux_2.4-3build2_amd64.deb ...
    default: Unpacking python-selinux (2.4-3build2) ...
    default: Processing triggers for man-db (2.7.5-1) ...
    default: Setting up libyaml-0-2:amd64 (0.1.6-3) ...
    default: Setting up python-markupsafe (0.23-2build2) ...
    default: Setting up python-jinja2 (2.8-1) ...
    default: Setting up python-six (1.10.0-3) ...
    default: Setting up python-ecdsa (0.13-2) ...
    default: Setting up python-paramiko (1.16.0-1ubuntu0.2) ...
    default: Setting up python-pkg-resources (20.7.0-1) ...
    default: Setting up python-yaml (3.11-3build1) ...
    default: Setting up python-httplib2 (0.9.1+dfsg-1) ...
    default: Setting up ieee-data (20150531.1) ...
    default: Setting up python-netaddr (0.7.18-1) ...
    default: Setting up ansible (2.0.0.2-2ubuntu1.1) ...
    default: Setting up python-selinux (2.4-3build2) ...
    default: Processing triggers for libc-bin (2.23-0ubuntu10) ...
==> default: Running provisioner: shell...
    default: Running: inline script
    default: PyBossa provisioning with Ansible...
    default: 
    default: PLAY ***************************************************************************
    default: 
    default: TASK [setup] *******************************************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [Check Ubuntu 16.04 running] **********************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [update apt cache] ********************************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [install git] *************************************************************
    default: changed: [127.0.0.1]
    default: 
    default: TASK [install Python] **********************************************************
    default: changed: [127.0.0.1] => (item=[u'python', u'python-dev', u'python-virtualenv', u'python-setuptools', u'python-pip'])
    default: 
    default: TASK [install PyBossa build requirements] **************************************
    default: changed: [127.0.0.1] => (item=[u'build-essential', u'libjpeg-dev', u'libssl-dev', u'swig', u'libffi-dev', u'dbus', u'libdbus-1-dev', u'libdbus-glib-1-dev', u'libsasl2-dev', u'libldap2-dev', u'libssl-dev', u'libldap2-dev'])
    default: 
    default: TASK [install PostgreSQL] ******************************************************
    default: changed: [127.0.0.1] => (item=[u'postgresql', u'postgresql-server-dev-all', u'libpq-dev', u'python-psycopg2'])
    default: 
    default: TASK [start PostgreSQL service] ************************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [install Redis] ***********************************************************
    default: changed: [127.0.0.1]
    default: 
    default: TASK [start Redis service] *****************************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [install Redis Sentinel] **************************************************
    default: changed: [127.0.0.1]
    default: 
    default: TASK [copy Redis Sentinel config] **********************************************
    default: changed: [127.0.0.1]
    default: 
    default: TASK [copy Redis Sentinel systemd config] **************************************
    default: changed: [127.0.0.1]
    default: 
    default: TASK [start Sentinel and enable it at boot] ************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [upgrade pip itself] ******************************************************
    default: ok: [127.0.0.1]
    default: 
    default: TASK [install PyBossa virtualenv packages, can take some time...] **************
```
And after waiting like almost 30 min nothing is happening and the box has switched to `paused` state and I can't interact with it...

## What I tried
First destroy the vagrant and restart it => nothing new, same...
Stop the process and I get this : 
```
^X^C/opt/vagrant/embedded/gems/2.2.3/gems/concurrent-ruby-1.1.4/lib/concurrent/collection/map/mri_map_backend.rb:18:in `synchronize': can't be called from trap context (ThreadError)
	from /opt/vagrant/embedded/gems/2.2.3/gems/concurrent-ruby-1.1.4/lib/concurrent/collection/map/mri_map_backend.rb:18:in `[]='
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n.rb:358:in `normalize_key'
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n.rb:298:in `normalize_keys'
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n/backend/simple.rb:84:in `lookup'
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n/backend/base.rb:30:in `translate'
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n.rb:185:in `block in translate'
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n.rb:181:in `catch'
	from /opt/vagrant/embedded/gems/2.2.3/gems/i18n-1.1.1/lib/i18n.rb:181:in `translate'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/action/runner.rb:59:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:49:in `block in fire_callbacks'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:49:in `each'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:49:in `fire_callbacks'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/util/busy.rb:33:in `block (2 levels) in register'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:127:in `join'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:127:in `block in run'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:65:in `each'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/batch_action.rb:65:in `run'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:280:in `block (2 levels) in batch'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:275:in `tap'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:275:in `block in batch'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:274:in `synchronize'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:274:in `batch'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/plugins/commands/up/command.rb:97:in `execute'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/cli.rb:58:in `execute'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/lib/vagrant/environment.rb:291:in `cli'
	from /opt/vagrant/embedded/gems/2.2.3/gems/vagrant-2.2.3/bin/vagrant:182:in `<main>'
```

I don't know what I'm doing wrong. Please advice me.

**Comment by teleyinex** [comment]
Hi,

We know that there're some issues within Windows 7. Can you try on another machine? I only have GNU/Linux machines, so I cannot test it on Windows. Apologies.

**Comment by ophyr** [comment]
@teleyinex I'm running everything from my Linux machine, keep just in mind that this linux is a VM running in my windows 7.

**Comment by ophyr** [comment]
@teleyinex The box is paused, I suppose the installation never finish... 
```
[root@ipf7028 pybossa]# vagrant global-status
id       name    provider   state  directory                           
-----------------------------------------------------------------------
47c12a7  default virtualbox paused /data/molecule/Pybossa/pybossa      
 
The above shows information about all known Vagrant environments
on this machine. This data is cached and may not be completely
up-to-date (use "vagrant global-status --prune" to prune invalid
entries). To interact with any of the machines, you can go to that
directory and run Vagrant, or you can use the ID directly with
Vagrant commands from any directory. For example:
"vagrant destroy 1a2b3c4d"
```

When I try to restart I get this : 
```
[root@ipf7028 pybossa]# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: There was a problem while downloading the metadata for your box
==> default: to check for updates. This is not an error, since it is usually due
==> default: to temporary network problems. This is just a warning. The problem
==> default: encountered was:
==> default: 
==> default: Could not resolve host: vagrantcloud.com
==> default: 
==> default: If you want to check for box updates, verify your network connection
==> default: is valid and try again.
==> default: Unpausing the VM...
```

I will try to destroy it and restart the whole process because I have no clue...

**Comment by ophyr** [comment]
I don't know if it's important somewhere, but I didn't have enough disk space to first deploy vagrant space, so I changed the environment variable VAGRANT_HOME somewhere with more disk space (about 10Gb) same for VirtualBox.

**Comment by ophyr** [comment]
I was able to delete the inaccessible vms through command line VirtualBox, here the solution : 
```
[root@ipf7028 ~]# VBoxManage list vms
"<inaccessible>" {f9214812-bb7a-4eb1-8a0a-8b6f08acf234}
[root@ipf7028 ~]# VBoxManage unregistervm {f9214812-bb7a-4eb1-8a0a-8b6f08acf234}
[root@ipf7028 ~]# VBoxManage list vms
"<inaccessible>" {5692c5de-5571-4c38-828e-4cf657f07f2f}
[root@ipf7028 ~]# VBoxManage unregistervm {5692c5de-5571-4c38-828e-4cf657f07f2f}
[root@ipf7028 ~]# VBoxManage list vms
```

**Comment by ophyr** [comment]
Okay I think I got the problem... Started downloading around 11h15, installation started 20mins later and stop like before on the line 
```
default: TASK [install PyBossa virtualenv packages, can take some time...] **************
```
And a pop-up open 
```
The volume "Filesystem root" has only 136.0 MB disk space remaining.
```
I should have paid attention to this last time... So it is related to disk space (again), but in VirtualBox preferences I did change the location for "Default Machine Folder" although my pybossa vm seems to be stored in Filesystem root... Have you an idea where I change that ?

**Comment by teleyinex** [comment]
I guess this could be because you didn't destroy the VM. Can you delete it completely, and try again? It should now respect your new configuration.

**Comment by ophyr** [comment]
I already deleted and restarted from scratch as I explained in my previous post.
The error is related to disk space issue, somewhere there is an information where to store the pybossa VM and I need to change that. For now it seems to be in filesystem root.

**Comment by ophyr** [comment]
Okey maybe I found the solution, I just need to move the default machinefolder vor VMs through command line : 
```
VBoxManage list systemproperties | grep folder => to check actual one
VBoxManage setproperty machinefolder to/new/path
```
And restart the process from beginning once again !

**Comment by teleyinex** [comment]
Ha. I thought that when you did it via the GUI it should work. Please, keep me posted. We will udpate the docs for users in case this solves the issue.

**Comment by ophyr** [comment]
Sooooooooooooooooooooooooooooooooooooooooo
This worked well, thank you for your support, and yes you can update the docs :)

**Comment by teleyinex** [comment]
Thanks to you for helping us debugging it, and also for solving it :D 

The PR for the docs is here: https://github.com/Scifabric/docs.pybossa.com/pull/48

**Comment by assetozen** [comment]
i have tried all resume,reload,suspend and also other troubleshooting methods.
Funny that it has worked when i just restarted my PC.
