### ISSUE TITLE
TemplateNotFound with version v2.13.1

### ISSUE THREAD

**Issue by vudangngoc** [Scifabric/pybossa#1948]
I checkout then follow the installation guide, the server start successfully but there is an exception when I access http://localhost:5000
127.0.0.1 - - [14/Dec/2019 03:23:31] "GET / HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1748, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/home/pooh/git/pybossa/pybossa/core.py", line 487, in _server_error
    return handle_content_type(response)
  File "/home/pooh/git/pybossa/pybossa/util.py", line 133, in handle_content_type
    return render_template(template, **data), error_code
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/pooh/git/pybossa/env/lib/python2.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: 500.html

**Comment by teleyinex** [comment]
Did you clone the repository with the --recursive flag? Otherwise, be sure to check that your theme folder has a default one with several files in it.
