### ISSUE TITLE
url = opts.pop('url') KeyError: 'url'

### ISSUE THREAD

**Issue by arthurlutz** [Scifabric/pybossa#224]
switched to a postgres configuration

$ python cli.py db_create
Twitter singin disabled
<type 'exceptions.KeyError'>
('FACEBOOK_APP_ID',)
'FACEBOOK_APP_ID'
Facebook singin disabled
<type 'exceptions.KeyError'>
('GOOGLE_CLIENT_ID',)
'GOOGLE_CLIENT_ID'
Google singin disabled
Traceback (most recent call last):
  File "cli.py", line 86, in <module>
    _main(locals())
  File "cli.py", line 81, in _main
    _methods[method](*args[1:])
  File "cli.py", line 20, in db_create
    command.stamp(alembic_cfg,"head")
  File "/home/arthur/local/virtualenvs/pybossa/local/lib/python2.7/site-packages/alembic/command.py", line 212, in stamp
    script.run_env()
  File "/home/arthur/local/virtualenvs/pybossa/local/lib/python2.7/site-packages/alembic/script.py", line 191, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/home/arthur/local/virtualenvs/pybossa/local/lib/python2.7/site-packages/alembic/util.py", line 185, in load_python_file
    module = imp.load_source(module_id, path, open(path, 'rb'))
  File "alembic/env.py", line 70, in <module>
    run_migrations_online()
  File "alembic/env.py", line 53, in run_migrations_online
    poolclass=pool.NullPool)
  File "/home/arthur/local/virtualenvs/pybossa/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 355, in engine_from_config
    url = opts.pop('url')
KeyError: 'url'

**Comment by bajiya2024** [comment]
how fix it

**Comment by teleyinex** [comment]
I have created today a new DB today using cli.py and it works without problems. What's the issue? This is from 2012.

**Comment by DinaTaklit** [comment]
For me I got a similar issue after commenting `sqlalchemy.url` line in `alembic.ini` file so I got this error  once I run the migration 
```error 
...
  File "migrations\env.py", line 90, in run_migrations_online    
    engine_from_config(
  File "D:\Dev\Sciigo\MySenseAI\backend\venv\lib\site-packages\sqlalchemy\engine\create.py", line 754, in engine_from_config      
    url = options.pop("url")
KeyError: 'url'
```
So I fixed it by returning back `sqlalchemy.url` but since I did not want to reveal the password of my connection I leave it blank and in env.py I set the value of `sqlalchemy.url`

```py
from config import settings

config.set_main_option(
    "sqlalchemy.url", settings.database_url.replace("postgres://", "postgresql+asyncpg://", 1))
```

Check this stack answer [Is it possible to store the alembic connect string outside of alembic.ini?](https://stackoverflow.com/questions/22178339/is-it-possible-to-store-the-alembic-connect-string-outside-of-alembic-ini/72916960#72916960) for more detail.
