### ISSUE TITLE
Got "500 - Internal Server Error"

### ISSUE THREAD

**Issue by hawkwang** [Scifabric/pybossa#731]
After install server based on install instruction, just "python run.py", 
and then I want to launch web browser with url "http://localhost:5000".
## But I got following error message on console:
- Running on http://0.0.0.0:5000/
  127.0.0.1 - - [18/Apr/2014 15:10:31] "GET / HTTP/1.1" 500 -
  Error on request:
  Traceback (most recent call last):
  File "/home/hawkwang/Tools/pybossa/env/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/hawkwang/Tools/pybossa/env/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/hawkwang/Tools/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/home/hawkwang/Tools/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/hawkwang/Tools/pybossa/env/lib/python2.7/site-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/home/hawkwang/Tools/pybossa/pybossa/core.py", line 243, in server_error
    return render_template('500.html'), 500
  File "/home/hawkwang/Tools/pybossa/env/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  ...
  ---------------------------------------------------------------------------------------------
## And the page displayed content as follows:

Internal Server Error
## The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

So, what's wrong with the codes?
I will try tox later.

Regards,
Hawk

**Comment by cravindra** [comment]
I had the same issue today. I made the mistake of running 

`git clone https://github.com/Scifabric/pybossa`

instead of

`git clone --recursive https://github.com/Scifabric/pybossa`

So the template files were unavailable. I'm just putting this here for anyone else looking.

**Comment by teleyinex** [comment]
Thanks! We've it in the docs, but maybe it's not too clear :-)

https://docs.pybossa.com/installation/guide/
